### PR TITLE
Intitial 1.20.1 Update by rocketstrong

### PR DESCRIPTION
**Pull request by rocketstrong600**
had some free time so i updated the mod to "1.20.1". I have redone the build scripts and did as much of the code migration as i could. i do believe there is a problem with one of the mixins still and some logic changes in Valkarian skies those do appear to be causing a few issues.

### CODE REVIEW

**Comment by rocketstrong600** [comment]
the mixins may be fine it was an earlier message reporting mixing in to a deprecated function that i am reporting on.

**Comment by TheDespawned** [comment]
Sounds great, when can we expect a full release on Curse?

**Comment by Endalion** [comment]
> some logic changes in Valkarian skies those do appear to be causing a few issues.

Could you list out these issues if they still exist?

**Comment by rocketstrong600** [comment]
once i found the actual vs core and vs match-up for the VS released on Modritnth the issues went away. just typical vs bugs that exist with other addons. I did encounter the track being stuck on without any connection to a create rotation source but didn't have the debugger going and haven't been able to reproduce.

**Pull request merged**
